# Generated by Django 5.2.16 on 2026-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('header', 'Шапка'), ('hero', 'Перший екран'), ('about', 'Про мене'), ('formats', 'Формати'), ('faq', 'Питання'), ('contacts', 'Контакти')], default='contacts', max_length=32)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('won', 'Успішна'), ('lost', 'Відхилена')], default='new', max_length=32)),
                ('admin_note', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('utm_source', models.CharField(blank=True, max_length=128)),
                ('utm_medium', models.CharField(blank=True, max_length=128)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
