# Generated by Django 5.2.16 on 2026-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='language',
            field=models.CharField(default='ru', max_length=8, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=255, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('header', 'Шапка'), ('hero', 'Первый экран'), ('about', 'Обо мне'), ('formats', 'Форматы'), ('faq', 'Вопросы'), ('contacts', 'Контакты')], default='contacts', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('won', 'Успешная'), ('lost', 'Отклонена')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=128, verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип перехода'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=128, verbose_name='Источник перехода'),
        ),
    ]
