# Generated by Django 5.2.16 on 2026-07-31 14:16

import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128)),
                ('role_ru', models.CharField(blank=True, max_length=255)),
                ('role_en', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='reviews/')),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
    ]
