# Generated by Django 5.2.16 on 2026-08-12 12:55

import django.core.validators
import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_author_name_bilingual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at', 'pk'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='На сайте показываются только активные (одобренные) отзывы.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_public_submission',
            field=models.BooleanField(default=False, verbose_name='Публичная заявка'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=src.core.fields.WebPImageField(blank=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
