# Generated by Django 5.2.16 on 2026-08-12 13:39

import django.utils.timezone
from django.db import migrations, models


def fill_null_created_at(apps, schema_editor):
    Testimonial = apps.get_model("reviews", "Testimonial")
    now = django.utils.timezone.now()
    Testimonial.objects.filter(created_at__isnull=True).update(created_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_webp_image_field"),
    ]

    operations = [
        migrations.RunPython(fill_null_created_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата",
            ),
        ),
    ]
