# Generated by Django 5.2.16 on 2026-08-12 14:11

import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_testimonial_created_at_non_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name_ru',
            field=models.CharField(max_length=128, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=src.core.fields.WebPImageField(blank=True, upload_to='reviews/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Роль / подпись'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Роль / подпись'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
    ]
