# Generated by Django 5.2.16 on 2026-07-31 14:16

import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_ru', models.CharField(blank=True, max_length=255)),
                ('alt_en', models.CharField(blank=True, max_length=255)),
                ('caption_ru', models.CharField(blank=True, max_length=255)),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('col_span', models.PositiveSmallIntegerField(default=1)),
                ('row_span', models.PositiveSmallIntegerField(default=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
    ]
