# Generated by Django 5.2.16 on 2026-08-12 12:55

import src.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryphoto_static_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='gallery/'),
        ),
    ]
