# Generated by Django 5.2.16 on 2026-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_webp_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='static_image',
            field=models.CharField(blank=True, help_text='Внутренний путь к файлу. Обычно не меняется.', max_length=255),
        ),
    ]
