# Generated by Django 5.2.16 on 2026-08-12 14:11

import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryphoto_static_image_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='alt_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='col_span',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='row_span',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='static_image',
            field=models.CharField(blank=True, help_text='Внутренний путь к файлу. Обычно не меняется.', max_length=255, verbose_name='Внутренний файл'),
        ),
    ]
