# Generated by Django 5.2.16 on 2026-07-31 14:16

import django.db.models.deletion
import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=128)),
                ('title_en', models.CharField(blank=True, max_length=128)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('price_text_ru', models.CharField(blank=True, max_length=128)),
                ('price_text_en', models.CharField(blank=True, max_length=128)),
                ('label_ru', models.CharField(blank=True, help_text='Напр. Формат I', max_length=64)),
                ('label_en', models.CharField(blank=True, max_length=64)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Формат послуги',
                'verbose_name_plural': 'Формати послуг',
                'ordering': ['order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=255)),
                ('text_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='formats.serviceformat')),
            ],
            options={
                'verbose_name': 'Пункт формату',
                'verbose_name_plural': 'Пункти формату',
                'ordering': ['order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
    ]
