# Generated by Django 5.2.16 on 2026-08-12 12:55

import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0002_serviceformat_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceformat',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Формат услуги', 'verbose_name_plural': 'Форматы услуг'},
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='formats/'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
