# Generated by Django 5.2.16 on 2026-08-12 14:11

import django.db.models.deletion
import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0003_webp_image_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatfeature',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Пункт формата', 'verbose_name_plural': 'Пункты формата'},
        ),
        migrations.AlterField(
            model_name='formatfeature',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='formatfeature',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='formats.serviceformat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='formatfeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='formatfeature',
            name='text_ru',
            field=models.CharField(max_length=255, verbose_name='Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='formats/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='label_en',
            field=models.CharField(blank=True, max_length=64, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='label_ru',
            field=models.CharField(blank=True, help_text='Напр. Формат I', max_length=64, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='price_text_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='price_text_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='serviceformat',
            name='title_ru',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
