# Generated by Django 5.2.16 on 2026-08-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='telegramchatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Чат Telegram', 'verbose_name_plural': 'Чаты Telegram'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('site_user', 'Пользователь сайта'), ('telegram_admin', 'Админ Telegram'), ('system', 'Система')], max_length=32, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.telegramchatsession', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID сообщения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='telegramchatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='telegramchatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], db_index=True, default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramchatsession',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramchatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='telegramchatsession',
            name='user_identifier',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Пользователь'),
        ),
    ]
