# Generated by Django 5.2.16 on 2026-07-31 14:16

import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=64, unique=True)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Полина', max_length=128)),
                ('logo', models.ImageField(blank=True, upload_to='brand/')),
                ('phone', models.CharField(blank=True, default='+7 000 000-00-00', max_length=64)),
                ('email', models.EmailField(blank=True, default='hello@example.com', max_length=254)),
                ('telegram_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('copyright_name', models.CharField(default='Полина', max_length=128)),
                ('location_ru', models.CharField(blank=True, default='Москва, по договорённости', max_length=255)),
                ('location_en', models.CharField(blank=True, default='Moscow, by arrangement', max_length=255)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('privacy', 'Політика'), ('site', 'Сайт')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('text_ru', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('video_file', models.FileField(blank=True, upload_to='blocks/video/')),
                ('video_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блок вмісту',
                'verbose_name_plural': 'Блоки вмісту',
                'ordering': ['page', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeAboutSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Про мене',
                'verbose_name_plural': 'Головна — Про мене',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeContactsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Контакти',
                'verbose_name_plural': 'Головна — Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeFaqSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Питання',
                'verbose_name_plural': 'Головна — Питання',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeFormatsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Формати',
                'verbose_name_plural': 'Головна — Формати',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeGallerySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Галерея',
                'verbose_name_plural': 'Головна — Галерея',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeTestimonialsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Відгуки',
                'verbose_name_plural': 'Головна — Відгуки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
