# Generated by Django 5.2.16 on 2026-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_location_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePersonalitySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Особистість',
                'verbose_name_plural': 'Головна — Особистість',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+380 00 000 00 00', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, default='https://t.me/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/'),
        ),
    ]
