# Generated by Django 5.2.16 on 2026-08-11 09:02

import django.core.validators
import src.core.fill_style
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personality_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('header', 'Шапка'), ('hero', 'Hero'), ('about', 'Про мене'), ('personality', 'Особистість'), ('gallery', 'Галерея'), ('formats', 'Формати'), ('testimonials', 'Відгуки'), ('faq', 'Питання'), ('contacts', 'Контакти'), ('footer', 'Підвал')], max_length=32, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('bg_fill_type', models.CharField(blank=True, choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='', max_length=16, verbose_name='Фон — тип')),
                ('bg_solid_color', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон — колір')),
                ('bg_gradient_start', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон — градієнт від')),
                ('bg_gradient_end', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон — градієнт до')),
                ('bg_gradient_angle', models.PositiveSmallIntegerField(blank=True, default=180, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Фон — кут')),
                ('btn_primary_fill_type', models.CharField(blank=True, choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='', max_length=16, verbose_name='Primary — тип')),
                ('btn_primary_solid_color', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Primary — колір')),
                ('btn_primary_gradient_start', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Primary — градієнт від')),
                ('btn_primary_gradient_end', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Primary — градієнт до')),
                ('btn_primary_gradient_angle', models.PositiveSmallIntegerField(blank=True, default=180, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Primary — кут')),
                ('btn_secondary_fill_type', models.CharField(blank=True, choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='', max_length=16, verbose_name='Secondary — тип')),
                ('btn_secondary_solid_color', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Secondary — колір')),
                ('btn_secondary_gradient_start', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Secondary — градієнт від')),
                ('btn_secondary_gradient_end', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Secondary — градієнт до')),
                ('btn_secondary_gradient_angle', models.PositiveSmallIntegerField(blank=True, default=180, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Secondary — кут')),
                ('btn_header_fill_type', models.CharField(blank=True, choices=[('solid', 'Однотонний'), ('gradient', 'Градієнт')], default='', max_length=16, verbose_name='Header CTA — тип')),
                ('btn_header_solid_color', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Header CTA — колір')),
                ('btn_header_gradient_start', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Header CTA — градієнт від')),
                ('btn_header_gradient_end', models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Header CTA — градієнт до')),
                ('btn_header_gradient_angle', models.PositiveSmallIntegerField(blank=True, default=180, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Header CTA — кут')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стиль секції',
                'verbose_name_plural': 'Стилі секцій',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='SiteChatSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чат',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteErrorsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінки помилок',
                'verbose_name_plural': 'Сторінки помилок',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал',
                'verbose_name_plural': 'Підвал',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteUiSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Інтерфейс і форми',
                'verbose_name_plural': 'Інтерфейс і форми',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ThemeStylesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Стилі',
                'verbose_name_plural': 'Стилі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='MAISON POLINA', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_name',
            field=models.CharField(default='MAISON POLINA', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, default='Nova Koncha-Zaspa RC', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_ru',
            field=models.CharField(blank=True, default='ЖК «Нова Конча-Заспа»', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+380 95 472 7859', max_length=64),
        ),
    ]
