# Generated by Django 5.2.16 on 2026-08-11 15:06

import django.core.validators
import src.core.fill_style
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteblock_oyra_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionstyle',
            options={'ordering': ['section'], 'verbose_name': 'Стиль секции', 'verbose_name_plural': 'Стили секций'},
        ),
        migrations.AlterModelOptions(
            name='themestylessettings',
            options={'verbose_name': 'Цвета и кнопки', 'verbose_name_plural': 'Цвета и кнопки'},
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='bg_fill_type',
            field=models.CharField(blank=True, choices=[('solid', 'Один цвет'), ('gradient', 'Градиент')], default='', max_length=16, verbose_name='Фон: как залить'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='bg_gradient_angle',
            field=models.PositiveSmallIntegerField(blank=True, default=180, help_text='От 0 до 360. Например, 180 — сверху вниз.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Фон: угол градиента (°)'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='bg_gradient_end',
            field=models.CharField(blank=True, default='', help_text='Второй цвет градиента.', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон: градиент — конец'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='bg_gradient_start',
            field=models.CharField(blank=True, default='', help_text='Первый цвет градиента.', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон: градиент — начало'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='bg_solid_color',
            field=models.CharField(blank=True, default='', help_text='Если выбран «Один цвет». Пример: #4c0d13', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Фон: цвет'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_header_fill_type',
            field=models.CharField(blank=True, choices=[('solid', 'Один цвет'), ('gradient', 'Градиент')], default='', max_length=16, verbose_name='Кнопка в шапке: как залить'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_header_gradient_angle',
            field=models.PositiveSmallIntegerField(blank=True, default=180, help_text='От 0 до 360. Например, 180 — сверху вниз.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Кнопка в шапке: угол градиента (°)'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_header_gradient_end',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Кнопка в шапке: градиент — конец'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_header_gradient_start',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Кнопка в шапке: градиент — начало'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_header_solid_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Кнопка в шапке: цвет'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_primary_fill_type',
            field=models.CharField(blank=True, choices=[('solid', 'Один цвет'), ('gradient', 'Градиент')], default='', max_length=16, verbose_name='Главная кнопка: как залить'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_primary_gradient_angle',
            field=models.PositiveSmallIntegerField(blank=True, default=180, help_text='От 0 до 360. Например, 180 — сверху вниз.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Главная кнопка: угол градиента (°)'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_primary_gradient_end',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Главная кнопка: градиент — конец'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_primary_gradient_start',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Главная кнопка: градиент — начало'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_primary_solid_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Главная кнопка: цвет'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_secondary_fill_type',
            field=models.CharField(blank=True, choices=[('solid', 'Один цвет'), ('gradient', 'Градиент')], default='', max_length=16, verbose_name='Вторая кнопка: как залить'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_secondary_gradient_angle',
            field=models.PositiveSmallIntegerField(blank=True, default=180, help_text='От 0 до 360. Например, 180 — сверху вниз.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Вторая кнопка: угол градиента (°)'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_secondary_gradient_end',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Вторая кнопка: градиент — конец'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_secondary_gradient_start',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Вторая кнопка: градиент — начало'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='btn_secondary_solid_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[src.core.fill_style.validate_hex_color], verbose_name='Вторая кнопка: цвет'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='label',
            field=models.CharField(blank=True, help_text='Как секция называется в списке ниже.', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='section',
            field=models.CharField(choices=[('header', 'Шапка'), ('hero', 'Первый экран (Hero)'), ('about', 'Обо мне'), ('personality', 'Личность'), ('gallery', 'Галерея'), ('formats', 'Форматы'), ('testimonials', 'Отзывы'), ('faq', 'Вопросы'), ('contacts', 'Контакты'), ('footer', 'Подвал')], max_length=32, unique=True, verbose_name='Секция'),
        ),
    ]
