# Generated by Django 5.2.16 on 2026-08-12 09:42

import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section_style_ru_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('facts', 'Внешность'), ('extras', 'Дополнительно')], db_index=True, max_length=16, verbose_name='Группа')),
                ('label_ru', models.CharField(blank=True, max_length=128, verbose_name='Название RU')),
                ('label_en', models.CharField(blank=True, max_length=128, verbose_name='Название EN')),
                ('value_ru', models.CharField(blank=True, max_length=255, verbose_name='Значение RU')),
                ('value_en', models.CharField(blank=True, max_length=255, verbose_name='Значение EN')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пункт личности',
                'verbose_name_plural': 'Пункты личности',
                'ordering': ['group', 'order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
    ]
