# Generated by Django 5.2.16 on 2026-08-12 12:55

import src.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_personality_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometa',
            name='og_image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='blocks/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=src.core.fields.WebPImageField(blank=True, upload_to='brand/'),
        ),
    ]
