# Generated by Django 5.2.16 on 2026-08-12 14:11

import src.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_webp_image_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='personalityitem',
            name='label_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='personalityitem',
            name='label_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='personalityitem',
            name='value_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='personalityitem',
            name='value_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='og_image',
            field=src.core.fields.WebPImageField(blank=True, upload_to='seo/', verbose_name='Картинка для соцсетей'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='page',
            field=models.CharField(max_length=64, unique=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='MAISON POLINA', max_length=128, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_name',
            field=models.CharField(default='MAISON POLINA', max_length=128, verbose_name='Имя в копирайте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='hello@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, default='Nova Koncha-Zaspa RC', max_length=255, verbose_name='Адрес / локация'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_ru',
            field=models.CharField(blank=True, default='ЖК «Нова Конча-Заспа»', max_length=255, verbose_name='Адрес / локация'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=src.core.fields.WebPImageField(blank=True, upload_to='brand/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+380 95 472 2029', max_length=64, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, default='https://t.me/', verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/', verbose_name='WhatsApp'),
        ),
    ]
