# Generated by Django 5.2.16 on 2026-08-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stored_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutsettings',
            options={'verbose_name': 'Восемь лет ярких впечатлений', 'verbose_name_plural': 'Восемь лет ярких впечатлений'},
        ),
        migrations.AlterModelOptions(
            name='homecontactssettings',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявка'},
        ),
        migrations.AlterModelOptions(
            name='homefaqsettings',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='homeformatssettings',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='homegallerysettings',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterModelOptions(
            name='homepersonalitysettings',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='hometestimonialssettings',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='siteheadersettings',
            options={'verbose_name': 'Шапка профиля', 'verbose_name_plural': 'Шапка профиля'},
        ),
    ]
