"""CMS sections part 2 — gallery through errors."""

from src.core.site_content_types import ContentSection, FieldGroup

MORE_CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug="gallery",
        page_slug="home",
        title="Галерея",
        sidebar_title="Галерея",
        sidebar_icon="photo_library",
        preview_url="/#gallery",
        description="Заголовок, подписи карусели и фото. Снимите «Активно», чтобы скрыть кадр.",
        visibility_key="gallery_section_visible",
        admin_model_name="homegallerysettings",
        has_gallery=True,
        blocks=(
            ("home", "gallery.eyebrow"),
            ("home", "gallery.title"),
            ("home", "gallery.title_accent"),
            ("site", "gallery.open"),
            ("site", "gallery.prev"),
            ("site", "gallery.next"),
            ("site", "lightbox.close"),
            ("site", "lightbox.prev"),
            ("site", "lightbox.next"),
            ("site", "carousel.prev"),
            ("site", "carousel.next"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок секции",
                ("gallery.eyebrow", "gallery.title", "gallery.title_accent"),
            ),
            FieldGroup(
                "Подписи просмотра",
                (
                    "gallery.open",
                    "gallery.prev",
                    "gallery.next",
                    "lightbox.close",
                    "lightbox.prev",
                    "lightbox.next",
                    "carousel.prev",
                    "carousel.next",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="formats",
        page_slug="home",
        title="Услуги",
        sidebar_title="Услуги",
        sidebar_icon="view_agenda",
        preview_url="/#services",
        description="Заголовок секции и карточки услуг. Снимите «Активно», чтобы скрыть формат.",
        visibility_key="formats_section_visible",
        admin_model_name="homeformatssettings",
        has_formats=True,
        blocks=(
            ("home", "formats.eyebrow"),
            ("home", "formats.title"),
            ("home", "formats.title_accent"),
            ("home", "formats.note"),
            ("site", "formats.featured_badge"),
            ("site", "formats.includes"),
            ("site", "formats.order_cta"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок",
                ("formats.eyebrow", "formats.title", "formats.title_accent"),
            ),
            FieldGroup("Примечание", ("formats.note",)),
            FieldGroup(
                "Подписи карточек",
                ("formats.featured_badge", "formats.includes", "formats.order_cta"),
            ),
        ),
    ),
    ContentSection(
        slug="testimonials",
        page_slug="home",
        title="Отзывы",
        sidebar_title="Отзывы",
        sidebar_icon="format_quote",
        preview_url="/#reviews",
        description="Заголовок, форма отзыва и список. Снимите «Активно», чтобы скрыть отзыв.",
        visibility_key="testimonials_section_visible",
        admin_model_name="hometestimonialssettings",
        has_testimonials=True,
        blocks=(
            ("home", "testimonials.eyebrow"),
            ("site", "review.cta"),
            ("site", "review.more"),
            ("site", "review.less"),
            ("site", "review.modal_title"),
            ("site", "review.form_name"),
            ("site", "review.form_rating"),
            ("site", "review.form_text"),
            ("site", "review.submit"),
            ("site", "review.success_title"),
            ("site", "review.success_text"),
        ),
        field_groups=(
            FieldGroup("Заголовок секции", ("testimonials.eyebrow", "review.cta")),
            FieldGroup("Карточка отзыва", ("review.more", "review.less")),
            FieldGroup(
                "Форма отзыва",
                (
                    "review.modal_title",
                    "review.form_name",
                    "review.form_rating",
                    "review.form_text",
                    "review.submit",
                    "review.success_title",
                    "review.success_text",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="faq",
        page_slug="home",
        title="Вопросы",
        sidebar_title="Вопросы",
        sidebar_icon="help",
        preview_url="/#faq",
        description="Заголовок и список вопросов. Снимите «Активно», чтобы скрыть пункт.",
        visibility_key="faq_section_visible",
        admin_model_name="homefaqsettings",
        has_faq=True,
        blocks=(
            ("home", "faq.eyebrow"),
            ("home", "faq.title"),
            ("home", "faq.title_accent"),
            ("home", "faq.cta"),
        ),
        field_groups=(
            FieldGroup("Заголовок", ("faq.eyebrow", "faq.title", "faq.title_accent")),
            FieldGroup("Кнопка", ("faq.cta",)),
        ),
    ),
    ContentSection(
        slug="contacts",
        page_slug="home",
        title="Заявка",
        sidebar_title="Заявка",
        sidebar_icon="mail",
        preview_url="/#contact",
        description="Фон, тексты слева, подписи формы и контакты.",
        visibility_key="contacts_section_visible",
        admin_model_name="homecontactssettings",
        settings_fields=("phone", "email", "telegram_url"),
        blocks=(
            ("home", "contacts.eyebrow"),
            ("home", "contacts.title"),
            ("home", "contacts.title_accent"),
            ("home", "contacts.lead"),
            ("home", "contacts.privacy_note"),
            ("site", "contacts.telegram_title"),
            ("site", "contacts.telegram_sub"),
            ("site", "contacts.form_label"),
            ("site", "contacts.bg"),
            ("site", "form.name"),
            ("site", "form.contact"),
            ("site", "form.message"),
            ("site", "form.consent_prefix"),
            ("site", "form.privacy_link"),
            ("site", "form.submit"),
            ("site", "form.service_hint"),
            ("site", "form.honeypot"),
            ("site", "lead.modal_title"),
            ("site", "lead.success_title"),
            ("site", "lead.success_text"),
            ("site", "ui.close"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок",
                ("contacts.eyebrow", "contacts.title", "contacts.title_accent"),
            ),
            FieldGroup("Текст слева", ("contacts.lead", "contacts.privacy_note")),
            FieldGroup(
                "Telegram и форма",
                (
                    "contacts.telegram_title",
                    "contacts.telegram_sub",
                    "contacts.form_label",
                    "contacts.bg",
                ),
            ),
            FieldGroup(
                "Поля формы",
                (
                    "form.name",
                    "form.contact",
                    "form.message",
                    "form.consent_prefix",
                    "form.privacy_link",
                    "form.submit",
                    "form.service_hint",
                    "form.honeypot",
                ),
            ),
            FieldGroup(
                "Окно заявки",
                (
                    "lead.modal_title",
                    "lead.success_title",
                    "lead.success_text",
                    "ui.close",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="privacy",
        page_slug="privacy",
        title="Политика конфиденциальности",
        sidebar_title="Политика конфиденциальности",
        sidebar_icon="policy",
        preview_url="/privacy/",
        description="Юридический текст страницы политики.",
        admin_model_name="privacysettings",
        blocks=(
            ("privacy", "title"),
            ("privacy", "body"),
        ),
        field_groups=(FieldGroup("Текст страницы", ("title", "body")),),
    ),
    ContentSection(
        slug="header",
        page_slug="site",
        title="Шапка профиля",
        sidebar_title="Шапка профиля",
        sidebar_icon="web_asset",
        preview_url="/",
        description="Логотип, телефон, пункты меню и подписи шапки.",
        admin_model_name="siteheadersettings",
        settings_fields=("logo", "brand_name", "phone"),
        blocks=(
            ("site", "nav.about"),
            ("site", "nav.gallery"),
            ("site", "nav.services"),
            ("site", "nav.reviews"),
            ("site", "nav.faq"),
            ("site", "nav.contact"),
            ("site", "header.nav_aria"),
            ("site", "header.menu_aria"),
            ("site", "header.cta"),
            ("site", "header.brand_line_1"),
            ("site", "header.brand_line_2"),
            ("site", "header.brand_aria"),
            ("site", "mobile.nav_aria"),
            ("site", "mobile.close"),
            ("site", "lang.aria"),
            ("site", "dock.aria"),
            ("site", "dock.home"),
            ("site", "dock.gallery"),
            ("site", "dock.contacts"),
        ),
        field_groups=(
            FieldGroup(
                "Меню",
                (
                    "nav.about",
                    "nav.gallery",
                    "nav.services",
                    "nav.reviews",
                    "nav.faq",
                    "nav.contact",
                ),
            ),
            FieldGroup(
                "Шапка",
                (
                    "header.brand_line_1",
                    "header.brand_line_2",
                    "header.brand_aria",
                    "header.cta",
                    "header.nav_aria",
                    "header.menu_aria",
                ),
            ),
            FieldGroup(
                "Мобильное / Dock",
                (
                    "mobile.nav_aria",
                    "mobile.close",
                    "lang.aria",
                    "dock.aria",
                    "dock.home",
                    "dock.gallery",
                    "dock.contacts",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="footer",
        page_slug="site",
        title="Подвал",
        sidebar_title="Подвал",
        sidebar_icon="horizontal_rule",
        preview_url="/#contact",
        description="Подписи подвала, политика и ссылки соцсетей.",
        admin_model_name="sitefootersettings",
        settings_fields=(
            "copyright_name",
            "location_ru",
            "location_en",
            "instagram_url",
            "whatsapp_url",
            "telegram_url",
            "email",
            "phone",
        ),
        blocks=(
            ("site", "footer.brand"),
            ("site", "footer.location_label"),
            ("site", "footer.contact_label"),
            ("site", "footer.menu_label"),
            ("site", "footer.menu_aria"),
            ("site", "footer.telegram_title"),
            ("site", "footer.telegram_sub"),
            ("site", "footer.menu_more"),
            ("site", "footer.privacy_1"),
            ("site", "footer.privacy_2"),
        ),
        field_groups=(
            FieldGroup(
                "Подписи",
                (
                    "footer.brand",
                    "footer.location_label",
                    "footer.contact_label",
                    "footer.menu_label",
                    "footer.menu_aria",
                ),
            ),
            FieldGroup(
                "Telegram и политика",
                (
                    "footer.telegram_title",
                    "footer.telegram_sub",
                    "footer.menu_more",
                    "footer.privacy_1",
                    "footer.privacy_2",
                ),
            ),
        ),
    ),
)
