"""CMS sections part 3 — UI chrome, chat, errors."""

from src.core.site_content_types import ContentSection, FieldGroup

UI_CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug="ui",
        page_slug="site",
        title="Интерфейс и формы",
        sidebar_title="Интерфейс",
        sidebar_icon="tune",
        preview_url="/",
        admin_model_name="siteuisettings",
        blocks=(
            ("site", "ui.close"),
            ("site", "form.name"),
            ("site", "form.contact"),
            ("site", "form.message"),
            ("site", "form.consent_prefix"),
            ("site", "form.privacy_link"),
            ("site", "form.submit"),
            ("site", "form.service_hint"),
            ("site", "form.honeypot"),
            ("site", "lead.modal_title"),
            ("site", "lead.success_title"),
            ("site", "lead.success_text"),
            ("site", "review.modal_title"),
            ("site", "review.form_name"),
            ("site", "review.form_rating"),
            ("site", "review.form_text"),
            ("site", "review.submit"),
            ("site", "review.success_title"),
            ("site", "review.success_text"),
            ("site", "review.cta"),
            ("site", "formats.featured_badge"),
            ("site", "formats.includes"),
            ("site", "formats.order_cta"),
            ("site", "contacts.telegram_title"),
            ("site", "contacts.telegram_sub"),
            ("site", "contacts.form_label"),
            ("site", "contacts.bg"),
            ("site", "gallery.open"),
            ("site", "gallery.prev"),
            ("site", "gallery.next"),
            ("site", "lightbox.close"),
            ("site", "lightbox.prev"),
            ("site", "lightbox.next"),
            ("site", "carousel.prev"),
            ("site", "carousel.next"),
            ("site", "personality.label_age"),
            ("site", "personality.label_eyes"),
            ("site", "personality.label_hair"),
            ("site", "personality.label_height"),
            ("site", "personality.label_weight"),
            ("site", "personality.label_measurements"),
            ("site", "personality.label_shoes"),
            ("site", "personality.label_clothing"),
            ("site", "personality.label_zodiac"),
            ("site", "personality.label_tattoo"),
            ("site", "personality.label_piercing"),
            ("site", "personality.label_flowers"),
            ("site", "personality.label_cuisine"),
            ("site", "personality.label_alcohol"),
            ("site", "personality.label_smoking"),
            ("site", "personality.portrait_alt"),
        ),
        field_groups=(
            FieldGroup(
                "Форма заявки",
                (
                    "form.name",
                    "form.contact",
                    "form.message",
                    "form.consent_prefix",
                    "form.privacy_link",
                    "form.submit",
                    "form.service_hint",
                    "form.honeypot",
                    "ui.close",
                ),
            ),
            FieldGroup(
                "Модалки",
                (
                    "lead.modal_title",
                    "lead.success_title",
                    "lead.success_text",
                    "review.modal_title",
                    "review.form_name",
                    "review.form_rating",
                    "review.form_text",
                    "review.submit",
                    "review.success_title",
                    "review.success_text",
                    "review.cta",
                ),
            ),
            FieldGroup(
                "Секции",
                (
                    "formats.featured_badge",
                    "formats.includes",
                    "formats.order_cta",
                    "contacts.telegram_title",
                    "contacts.telegram_sub",
                    "contacts.form_label",
                    "contacts.bg",
                ),
            ),
            FieldGroup(
                "Галерея / карусель",
                (
                    "gallery.open",
                    "gallery.prev",
                    "gallery.next",
                    "lightbox.close",
                    "lightbox.prev",
                    "lightbox.next",
                    "carousel.prev",
                    "carousel.next",
                ),
            ),
            FieldGroup(
                "Метки личности",
                (
                    "personality.label_age",
                    "personality.label_eyes",
                    "personality.label_hair",
                    "personality.label_height",
                    "personality.label_weight",
                    "personality.label_measurements",
                    "personality.label_shoes",
                    "personality.label_clothing",
                    "personality.label_zodiac",
                    "personality.label_tattoo",
                    "personality.label_piercing",
                    "personality.label_flowers",
                    "personality.label_cuisine",
                    "personality.label_alcohol",
                    "personality.label_smoking",
                    "personality.portrait_alt",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="chat",
        page_slug="site",
        title="Чат",
        sidebar_title="Чат",
        sidebar_icon="chat",
        preview_url="/",
        admin_model_name="sitechatsettings",
        blocks=(
            ("site", "chat.title"),
            ("site", "chat.subtitle"),
            ("site", "chat.open"),
            ("site", "chat.close"),
            ("site", "chat.panel_aria"),
            ("site", "chat.input_label"),
            ("site", "chat.placeholder"),
            ("site", "chat.send"),
            ("site", "chat.empty"),
            ("site", "chat.error_rate"),
            ("site", "chat.error_session"),
            ("site", "chat.error_send"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок и кнопки",
                (
                    "chat.title",
                    "chat.subtitle",
                    "chat.open",
                    "chat.close",
                    "chat.panel_aria",
                ),
            ),
            FieldGroup(
                "Поле ввода",
                ("chat.input_label", "chat.placeholder", "chat.send", "chat.empty"),
            ),
            FieldGroup(
                "Ошибки",
                ("chat.error_rate", "chat.error_session", "chat.error_send"),
            ),
        ),
    ),
    ContentSection(
        slug="errors",
        page_slug="site",
        title="Страницы ошибок",
        sidebar_title="Ошибки",
        sidebar_icon="error",
        preview_url="/",
        admin_model_name="siteerrorssettings",
        blocks=(
            ("site", "error.404_text"),
            ("site", "error.404_cta"),
            ("site", "error.500_text"),
            ("site", "error.500_cta"),
        ),
        field_groups=(
            FieldGroup("404", ("error.404_text", "error.404_cta")),
            FieldGroup("500", ("error.500_text", "error.500_cta")),
        ),
    ),
)
