from dataclasses import dataclass, field


@dataclass(frozen=True)
class FieldGroup:
    title: str
    keys: tuple[str, ...]


@dataclass(frozen=True)
class ContentSection:
    slug: str
    page_slug: str
    title: str
    blocks: tuple[tuple[str, str], ...]
    sidebar_title: str = ""
    sidebar_icon: str = "edit_note"
    preview_url: str = "/"
    description: str = ""
    visibility_key: str = ""
    field_groups: tuple[FieldGroup, ...] = field(default_factory=tuple)
    admin_model_name: str = ""
    has_gallery: bool = False


CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug="hero",
        page_slug="home",
        title="Hero",
        sidebar_title="Hero",
        sidebar_icon="image",
        preview_url="/",
        visibility_key="hero_section_visible",
        admin_model_name="homeherosettings",
        blocks=(
            ("home", "hero.title"),
            ("home", "hero.subtitle"),
            ("home", "hero.lead"),
            ("home", "hero.cta_primary"),
            ("home", "hero.cta_secondary"),
            ("home", "hero.tagline"),
            ("home", "hero.media"),
        ),
        field_groups=(
            FieldGroup("Тексти", ("hero.title", "hero.subtitle", "hero.lead", "hero.tagline")),
            FieldGroup("Кнопки", ("hero.cta_primary", "hero.cta_secondary")),
            FieldGroup("Медіа", ("hero.media",)),
        ),
    ),
    ContentSection(
        slug="about",
        page_slug="home",
        title="Про мене",
        sidebar_title="Про мене",
        sidebar_icon="person",
        preview_url="/#about",
        visibility_key="about_section_visible",
        admin_model_name="homeaboutsettings",
        blocks=(
            ("home", "about.eyebrow"),
            ("home", "about.title"),
            ("home", "about.title_accent"),
            ("home", "about.body_1"),
            ("home", "about.body_2"),
            ("home", "about.body_3"),
            ("home", "about.quote"),
            ("home", "about.stat_1_value"),
            ("home", "about.stat_1_label"),
            ("home", "about.stat_2_value"),
            ("home", "about.stat_2_label"),
            ("home", "about.stat_3_value"),
            ("home", "about.stat_3_label"),
            ("home", "about.cta"),
            ("home", "about.portrait"),
        ),
    ),
    ContentSection(
        slug="personality",
        page_slug="home",
        title="Особистість",
        sidebar_title="Особистість",
        sidebar_icon="badge",
        preview_url="/#personality",
        visibility_key="personality_section_visible",
        admin_model_name="homepersonalitysettings",
        blocks=(
            ("home", "personality.eyebrow"),
            ("home", "personality.title"),
            ("home", "personality.title_accent"),
            ("home", "personality.facts_title"),
            ("home", "personality.age"),
            ("home", "personality.eyes"),
            ("home", "personality.hair"),
            ("home", "personality.height"),
            ("home", "personality.weight"),
            ("home", "personality.measurements"),
            ("home", "personality.shoes"),
            ("home", "personality.clothing"),
            ("home", "personality.zodiac"),
            ("home", "personality.tattoo"),
            ("home", "personality.piercing"),
            ("home", "personality.flowers"),
            ("home", "personality.cuisine"),
            ("home", "personality.alcohol"),
            ("home", "personality.smoking"),
            ("home", "personality.extra_title"),
            ("home", "personality.extra_1"),
            ("home", "personality.extra_2"),
            ("home", "personality.extra_3"),
            ("home", "personality.languages"),
            ("home", "personality.respect"),
            ("home", "personality.education"),
            ("home", "personality.travel"),
            ("home", "personality.portrait"),
        ),
        field_groups=(
            FieldGroup("Заголовок", ("personality.eyebrow", "personality.title", "personality.title_accent")),
            FieldGroup(
                "Внешность",
                (
                    "personality.facts_title",
                    "personality.age",
                    "personality.eyes",
                    "personality.hair",
                    "personality.height",
                    "personality.weight",
                    "personality.measurements",
                    "personality.shoes",
                    "personality.clothing",
                    "personality.zodiac",
                    "personality.tattoo",
                    "personality.piercing",
                    "personality.flowers",
                    "personality.cuisine",
                    "personality.alcohol",
                    "personality.smoking",
                ),
            ),
            FieldGroup(
                "Додатково",
                (
                    "personality.portrait",
                    "personality.extra_title",
                    "personality.extra_1",
                    "personality.extra_2",
                    "personality.extra_3",
                    "personality.languages",
                    "personality.respect",
                    "personality.education",
                    "personality.travel",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="gallery",
        page_slug="home",
        title="Галерея",
        sidebar_title="Галерея",
        sidebar_icon="photo_library",
        preview_url="/#gallery",
        visibility_key="gallery_section_visible",
        admin_model_name="homegallerysettings",
        has_gallery=True,
        blocks=(
            ("home", "gallery.eyebrow"),
            ("home", "gallery.title"),
            ("home", "gallery.title_accent"),
        ),
    ),
    ContentSection(
        slug="formats",
        page_slug="home",
        title="Формати",
        sidebar_title="Формати",
        sidebar_icon="view_agenda",
        preview_url="/#services",
        visibility_key="formats_section_visible",
        admin_model_name="homeformatssettings",
        blocks=(
            ("home", "formats.eyebrow"),
            ("home", "formats.title"),
            ("home", "formats.title_accent"),
            ("home", "formats.note"),
        ),
    ),
    ContentSection(
        slug="testimonials",
        page_slug="home",
        title="Відгуки",
        sidebar_title="Відгуки",
        sidebar_icon="format_quote",
        preview_url="/#reviews",
        visibility_key="testimonials_section_visible",
        admin_model_name="hometestimonialssettings",
        blocks=(("home", "testimonials.eyebrow"),),
    ),
    ContentSection(
        slug="faq",
        page_slug="home",
        title="Питання",
        sidebar_title="Питання",
        sidebar_icon="help",
        preview_url="/#faq",
        visibility_key="faq_section_visible",
        admin_model_name="homefaqsettings",
        blocks=(
            ("home", "faq.eyebrow"),
            ("home", "faq.title"),
            ("home", "faq.title_accent"),
            ("home", "faq.cta"),
        ),
    ),
    ContentSection(
        slug="contacts",
        page_slug="home",
        title="Контакти",
        sidebar_title="Контакти",
        sidebar_icon="mail",
        preview_url="/#contact",
        visibility_key="contacts_section_visible",
        admin_model_name="homecontactssettings",
        blocks=(
            ("home", "contacts.eyebrow"),
            ("home", "contacts.title"),
            ("home", "contacts.title_accent"),
            ("home", "contacts.lead"),
            ("home", "contacts.privacy_note"),
        ),
    ),
    ContentSection(
        slug="privacy",
        page_slug="privacy",
        title="Політика конфіденційності",
        sidebar_title="Політика",
        sidebar_icon="policy",
        preview_url="/privacy/",
        admin_model_name="privacysettings",
        blocks=(
            ("privacy", "title"),
            ("privacy", "body"),
        ),
    ),
    ContentSection(
        slug="header",
        page_slug="site",
        title="Шапка",
        sidebar_title="Шапка",
        sidebar_icon="web_asset",
        preview_url="/",
        admin_model_name="siteheadersettings",
        blocks=(
            ("site", "nav.about"),
            ("site", "nav.gallery"),
            ("site", "nav.services"),
            ("site", "nav.reviews"),
            ("site", "nav.faq"),
            ("site", "nav.contact"),
            ("site", "header.nav_aria"),
            ("site", "header.menu_aria"),
            ("site", "header.cta"),
            ("site", "header.brand_line_1"),
            ("site", "header.brand_line_2"),
            ("site", "header.brand_aria"),
            ("site", "mobile.nav_aria"),
            ("site", "mobile.close"),
            ("site", "lang.aria"),
            ("site", "dock.aria"),
            ("site", "dock.home"),
            ("site", "dock.gallery"),
            ("site", "dock.contacts"),
        ),
        field_groups=(
            FieldGroup(
                "Меню",
                (
                    "nav.about",
                    "nav.gallery",
                    "nav.services",
                    "nav.reviews",
                    "nav.faq",
                    "nav.contact",
                ),
            ),
            FieldGroup(
                "Шапка",
                (
                    "header.brand_line_1",
                    "header.brand_line_2",
                    "header.brand_aria",
                    "header.cta",
                    "header.nav_aria",
                    "header.menu_aria",
                ),
            ),
            FieldGroup(
                "Мобільне / Dock",
                (
                    "mobile.nav_aria",
                    "mobile.close",
                    "lang.aria",
                    "dock.aria",
                    "dock.home",
                    "dock.gallery",
                    "dock.contacts",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="footer",
        page_slug="site",
        title="Підвал",
        sidebar_title="Підвал",
        sidebar_icon="horizontal_rule",
        preview_url="/#contact",
        admin_model_name="sitefootersettings",
        blocks=(
            ("site", "footer.brand"),
            ("site", "footer.location_label"),
            ("site", "footer.contact_label"),
            ("site", "footer.menu_label"),
            ("site", "footer.menu_aria"),
            ("site", "footer.telegram_title"),
            ("site", "footer.telegram_sub"),
            ("site", "footer.menu_more"),
            ("site", "footer.privacy_1"),
            ("site", "footer.privacy_2"),
        ),
    ),
    ContentSection(
        slug="ui",
        page_slug="site",
        title="Інтерфейс і форми",
        sidebar_title="Інтерфейс",
        sidebar_icon="tune",
        preview_url="/",
        admin_model_name="siteuisettings",
        blocks=(
            ("site", "ui.close"),
            ("site", "form.name"),
            ("site", "form.contact"),
            ("site", "form.message"),
            ("site", "form.consent_prefix"),
            ("site", "form.privacy_link"),
            ("site", "form.submit"),
            ("site", "form.service_hint"),
            ("site", "form.honeypot"),
            ("site", "lead.modal_title"),
            ("site", "lead.success_title"),
            ("site", "lead.success_text"),
            ("site", "review.modal_title"),
            ("site", "review.form_name"),
            ("site", "review.form_rating"),
            ("site", "review.form_text"),
            ("site", "review.submit"),
            ("site", "review.success_title"),
            ("site", "review.success_text"),
            ("site", "review.cta"),
            ("site", "formats.featured_badge"),
            ("site", "formats.includes"),
            ("site", "formats.order_cta"),
            ("site", "contacts.telegram_title"),
            ("site", "contacts.telegram_sub"),
            ("site", "contacts.form_label"),
            ("site", "contacts.bg"),
            ("site", "gallery.open"),
            ("site", "gallery.prev"),
            ("site", "gallery.next"),
            ("site", "lightbox.close"),
            ("site", "lightbox.prev"),
            ("site", "lightbox.next"),
            ("site", "carousel.prev"),
            ("site", "carousel.next"),
            ("site", "personality.label_age"),
            ("site", "personality.label_eyes"),
            ("site", "personality.label_hair"),
            ("site", "personality.label_height"),
            ("site", "personality.label_weight"),
            ("site", "personality.label_measurements"),
            ("site", "personality.label_shoes"),
            ("site", "personality.label_clothing"),
            ("site", "personality.label_zodiac"),
            ("site", "personality.label_tattoo"),
            ("site", "personality.label_piercing"),
            ("site", "personality.label_flowers"),
            ("site", "personality.label_cuisine"),
            ("site", "personality.label_alcohol"),
            ("site", "personality.label_smoking"),
            ("site", "personality.portrait_alt"),
        ),
        field_groups=(
            FieldGroup("Форма заявки", (
                "form.name", "form.contact", "form.message",
                "form.consent_prefix", "form.privacy_link", "form.submit",
                "form.service_hint", "form.honeypot", "ui.close",
            )),
            FieldGroup("Модалки", (
                "lead.modal_title", "lead.success_title", "lead.success_text",
                "review.modal_title", "review.form_name", "review.form_rating",
                "review.form_text", "review.submit", "review.success_title",
                "review.success_text", "review.cta",
            )),
            FieldGroup("Секції", (
                "formats.featured_badge", "formats.includes", "formats.order_cta",
                "contacts.telegram_title", "contacts.telegram_sub",
                "contacts.form_label", "contacts.bg",
            )),
            FieldGroup("Галерея / карусель", (
                "gallery.open", "gallery.prev", "gallery.next",
                "lightbox.close", "lightbox.prev", "lightbox.next",
                "carousel.prev", "carousel.next",
            )),
            FieldGroup("Мітки особистості", (
                "personality.label_age", "personality.label_eyes",
                "personality.label_hair", "personality.label_height",
                "personality.label_weight", "personality.label_measurements",
                "personality.label_shoes", "personality.label_clothing",
                "personality.label_zodiac", "personality.label_tattoo",
                "personality.label_piercing", "personality.label_flowers",
                "personality.label_cuisine", "personality.label_alcohol",
                "personality.label_smoking", "personality.portrait_alt",
            )),
        ),
    ),
    ContentSection(
        slug="chat",
        page_slug="site",
        title="Чат",
        sidebar_title="Чат",
        sidebar_icon="chat",
        preview_url="/",
        admin_model_name="sitechatsettings",
        blocks=(
            ("site", "chat.title"),
            ("site", "chat.subtitle"),
            ("site", "chat.open"),
            ("site", "chat.close"),
            ("site", "chat.panel_aria"),
            ("site", "chat.input_label"),
            ("site", "chat.placeholder"),
            ("site", "chat.send"),
            ("site", "chat.empty"),
            ("site", "chat.error_rate"),
            ("site", "chat.error_session"),
            ("site", "chat.error_send"),
        ),
    ),
    ContentSection(
        slug="errors",
        page_slug="site",
        title="Сторінки помилок",
        sidebar_title="Помилки",
        sidebar_icon="error",
        preview_url="/",
        admin_model_name="siteerrorssettings",
        blocks=(
            ("site", "error.404_text"),
            ("site", "error.404_cta"),
            ("site", "error.500_text"),
            ("site", "error.500_cta"),
        ),
    ),
)


def get_section(page_slug: str, section_slug: str) -> ContentSection | None:
    for section in CONTENT_SECTIONS:
        if section.page_slug == page_slug and section.slug == section_slug:
            return section
    return None
