"""CMS sections part 2 — gallery through errors."""

from src.core.site_content_types import ContentSection, FieldGroup

MORE_CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug="gallery",
        page_slug="home",
        title="Галерея",
        sidebar_title="Галерея",
        sidebar_icon="photo_library",
        preview_url="/#gallery",
        description="Заголовок секции и фото галереи.",
        visibility_key="gallery_section_visible",
        admin_model_name="homegallerysettings",
        has_gallery=True,
        blocks=(
            ("home", "gallery.eyebrow"),
            ("home", "gallery.title"),
            ("home", "gallery.title_accent"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок секции",
                ("gallery.eyebrow", "gallery.title", "gallery.title_accent"),
            ),
        ),
    ),
    ContentSection(
        slug="formats",
        page_slug="home",
        title="Форматы",
        sidebar_title="Форматы",
        sidebar_icon="view_agenda",
        preview_url="/#services",
        visibility_key="formats_section_visible",
        admin_model_name="homeformatssettings",
        blocks=(
            ("home", "formats.eyebrow"),
            ("home", "formats.title"),
            ("home", "formats.title_accent"),
            ("home", "formats.note"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок",
                ("formats.eyebrow", "formats.title", "formats.title_accent"),
            ),
            FieldGroup("Примечание", ("formats.note",)),
        ),
    ),
    ContentSection(
        slug="testimonials",
        page_slug="home",
        title="Отзывы",
        sidebar_title="Отзывы",
        sidebar_icon="format_quote",
        preview_url="/#reviews",
        visibility_key="testimonials_section_visible",
        admin_model_name="hometestimonialssettings",
        blocks=(("home", "testimonials.eyebrow"),),
        field_groups=(FieldGroup("Заголовок секции", ("testimonials.eyebrow",)),),
    ),
    ContentSection(
        slug="faq",
        page_slug="home",
        title="Вопросы",
        sidebar_title="Вопросы",
        sidebar_icon="help",
        preview_url="/#faq",
        visibility_key="faq_section_visible",
        admin_model_name="homefaqsettings",
        blocks=(
            ("home", "faq.eyebrow"),
            ("home", "faq.title"),
            ("home", "faq.title_accent"),
            ("home", "faq.cta"),
        ),
        field_groups=(
            FieldGroup("Заголовок", ("faq.eyebrow", "faq.title", "faq.title_accent")),
            FieldGroup("Кнопка", ("faq.cta",)),
        ),
    ),
    ContentSection(
        slug="contacts",
        page_slug="home",
        title="Контакты",
        sidebar_title="Контакты",
        sidebar_icon="mail",
        preview_url="/#contact",
        visibility_key="contacts_section_visible",
        admin_model_name="homecontactssettings",
        blocks=(
            ("home", "contacts.eyebrow"),
            ("home", "contacts.title"),
            ("home", "contacts.title_accent"),
            ("home", "contacts.lead"),
            ("home", "contacts.privacy_note"),
        ),
        field_groups=(
            FieldGroup(
                "Заголовок",
                ("contacts.eyebrow", "contacts.title", "contacts.title_accent"),
            ),
            FieldGroup("Текст", ("contacts.lead", "contacts.privacy_note")),
        ),
    ),
    ContentSection(
        slug="privacy",
        page_slug="privacy",
        title="Политика конфиденциальности",
        sidebar_title="Политика",
        sidebar_icon="policy",
        preview_url="/privacy/",
        admin_model_name="privacysettings",
        blocks=(
            ("privacy", "title"),
            ("privacy", "body"),
        ),
        field_groups=(FieldGroup("Текст страницы", ("title", "body")),),
    ),
    ContentSection(
        slug="header",
        page_slug="site",
        title="Шапка",
        sidebar_title="Шапка",
        sidebar_icon="web_asset",
        preview_url="/",
        admin_model_name="siteheadersettings",
        blocks=(
            ("site", "nav.about"),
            ("site", "nav.gallery"),
            ("site", "nav.services"),
            ("site", "nav.reviews"),
            ("site", "nav.faq"),
            ("site", "nav.contact"),
            ("site", "header.nav_aria"),
            ("site", "header.menu_aria"),
            ("site", "header.cta"),
            ("site", "header.brand_line_1"),
            ("site", "header.brand_line_2"),
            ("site", "header.brand_aria"),
            ("site", "mobile.nav_aria"),
            ("site", "mobile.close"),
            ("site", "lang.aria"),
            ("site", "dock.aria"),
            ("site", "dock.home"),
            ("site", "dock.gallery"),
            ("site", "dock.contacts"),
        ),
        field_groups=(
            FieldGroup(
                "Меню",
                (
                    "nav.about",
                    "nav.gallery",
                    "nav.services",
                    "nav.reviews",
                    "nav.faq",
                    "nav.contact",
                ),
            ),
            FieldGroup(
                "Шапка",
                (
                    "header.brand_line_1",
                    "header.brand_line_2",
                    "header.brand_aria",
                    "header.cta",
                    "header.nav_aria",
                    "header.menu_aria",
                ),
            ),
            FieldGroup(
                "Мобильное / Dock",
                (
                    "mobile.nav_aria",
                    "mobile.close",
                    "lang.aria",
                    "dock.aria",
                    "dock.home",
                    "dock.gallery",
                    "dock.contacts",
                ),
            ),
        ),
    ),
    ContentSection(
        slug="footer",
        page_slug="site",
        title="Подвал",
        sidebar_title="Подвал",
        sidebar_icon="horizontal_rule",
        preview_url="/#contact",
        admin_model_name="sitefootersettings",
        blocks=(
            ("site", "footer.brand"),
            ("site", "footer.location_label"),
            ("site", "footer.contact_label"),
            ("site", "footer.menu_label"),
            ("site", "footer.menu_aria"),
            ("site", "footer.telegram_title"),
            ("site", "footer.telegram_sub"),
            ("site", "footer.menu_more"),
            ("site", "footer.privacy_1"),
            ("site", "footer.privacy_2"),
        ),
        field_groups=(
            FieldGroup(
                "Подписи",
                (
                    "footer.brand",
                    "footer.location_label",
                    "footer.contact_label",
                    "footer.menu_label",
                    "footer.menu_aria",
                ),
            ),
            FieldGroup(
                "Telegram и политика",
                (
                    "footer.telegram_title",
                    "footer.telegram_sub",
                    "footer.menu_more",
                    "footer.privacy_1",
                    "footer.privacy_2",
                ),
            ),
        ),
    ),
)
