#!/usr/bin/env python3
"""Concatenate modular CSS into production bundles (site.css, pages/home.css).

Source files under static/css/ remain the editable source of truth.
Run: python3 scripts/build_css.py
Hooked into Vercel buildCommand before collectstatic.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "static" / "css"

SITE_PARTS = [
    "tokens.css",
    "fonts-lora.css",
    "reset.css",
    "typography.css",
    "base.css",
    "animations.css",
    "layout/header.css",
    "layout/footer.css",
    "components/button.css",
    "components/form.css",
    "components/modal.css",
    "components/card.css",
    "components/nav-mobile.css",
    "components/lang-switcher.css",
    "components/gallery.css",
    "components/carousel.css",
    "components/rating.css",
    "components/accordion.css",
    "components/chat-widget.css",
    "components/dock.css",
    "components/richtext.css",
]

HOME_PARTS = [
    "pages/home-1.css",
    "pages/home-1b.css",
    "pages/home-2.css",
    "pages/home-3.css",
]


def _bundle(parts: list[str], out_name: str) -> Path:
    chunks: list[str] = [
        f"/* AUTO-GENERATED by scripts/build_css.py — do not edit. Sources: {', '.join(parts)} */\n"
    ]
    for rel in parts:
        path = CSS / rel
        if not path.is_file():
            raise SystemExit(f"Missing CSS source: {path}")
        text = path.read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n/* --- {rel} --- */\n{text}\n")
    out = CSS / out_name
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(chunks), encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)} ({out.stat().st_size} bytes)")
    return out


def main() -> None:
    _bundle(SITE_PARTS, "site.css")
    _bundle(HOME_PARTS, "pages/home.css")


if __name__ == "__main__":
    main()
