# Generated by Django 5.2.16 on 2026-07-31 14:16

import src.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=255)),
                ('question_en', models.CharField(blank=True, max_length=255)),
                ('answer_ru', models.TextField()),
                ('answer_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання й відповіді',
                'ordering': ['order', 'pk'],
            },
            bases=(src.core.mixins.BilingualTextMixin, models.Model),
        ),
    ]
