# Generated by Django 5.2.16 on 2026-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_ru',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_ru',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
    ]
